# Fachgebiete.ps1
# Mapping: Fachgebiets-Nummer (Otn1-Wert des TK-Aerztefuehrers) -> Klartext-Bezeichnung.
# Quelle: <select id="Otn1"> aus tk-aerztefuehrer.html.

$Global:Fachgebiete = [ordered]@{
  '2524' = 'Akupunktur (Zusatzbezeichnung)'
  '3741' = 'Alle Richtlinienverfahren'
  '1'    = 'Allergologie'
  '2'    = 'Allgemeinmedizin'
  '2906' = 'analytische Psychotherapie (Richtlinie)'
  '3742' = 'analytische Psychotherapie fuer Kinder und Jugendliche (Richtlinie)'
  '80'   = 'Anaesthesiologie'
  '1554' = 'Anatomie'
  '917'  = 'Andrologie'
  '3752' = 'Angiologie -> Innere Medizin und Angiologie'
  '3'    = 'Arbeitsmedizin'
  '3735' = 'Aerztliches Qualitaetsmanagement'
  '4'    = 'Augenheilkunde'
  '77'   = 'Balneologie und Medizinische Klimatologie'
  '1008' = 'Bauchchirurgie (Viszeralchirurgie)'
  '2942' = 'Bauchchirurgie: Spezielle Viszeralchirurgie'
  '1092' = 'Betriebsmedizin'
  '1555' = 'Biochemie'
  '797'  = 'Brustkorb-Chirurgie (Thoraxchirurgie)'
  '6'    = 'Chirurgie'
  '962'  = 'Chirurgie: Spezielle Orthopaedische Chirurgie'
  '4688' = 'Dermatologie -> Haut- und Geschlechtskrankheiten'
  '1980' = 'Dermatopathologie / Dermatohistologie'
  '245'  = 'Diabetologie'
  '1786' = 'Diagnostische Radiologie -> Radiologie'
  '332'  = 'Enddarmerkrankungen (Proktologie)'
  '3753' = 'Endokrinologie und Diabetologie -> Innere Medizin und Endokrinologie und Diabetologie'
  '2889' = 'Ernaehrungsmedizin (Zusatzbezeichnung)'
  '369'  = 'Flugmedizin'
  '10'   = 'Frauenheilkunde und Geburtshilfe'
  '2324' = 'Funktionsdiagnostik und -therapie (Kammerzertifikat)'
  '3754' = 'Gastroenterologie -> Innere Medizin und Gastroenterologie'
  '2180' = 'Geburt: Spezielle Geburtshilfe u. Perinatalmedizin'
  '55'   = 'Gefaesschirurgie'
  '1670' = 'Genetik, medizinische'
  '3755' = 'Geriatrie -> Innere Medizin und Geriatrie'
  '3763' = 'Geriatrie / Klinische Geriatrie'
  '2115' = 'Gynaekologische Endokrinologie und Reproduktionsmedizin'
  '1825' = 'Gynaekologische Exfoliativ-Zytologie'
  '12'   = 'Hals-Nasen-Ohrenheilkunde'
  '3760' = 'Haematologie und Onkologie -> Innere Medizin und Haematologie und Onkologie'
  '1981' = 'Haemostaseologie'
  '376'  = 'Handchirurgie'
  '26'   = 'Hausarzt / Hausaerztin'
  '7'    = 'Haut- und Geschlechtskrankheiten'
  '1090' = 'Herzchirurgie'
  '13'   = 'Homoeopathie'
  '707'  = 'Hormonstoerungen -> Innere Medizin und Endokrinologie und Diabetologie'
  '1186' = 'Humangenetik'
  '1473' = 'Hygiene und Umweltmedizin'
  '4912' = 'Immunologie (Zusatzbezeichnung)'
  '1780' = 'Infektiologie'
  '1671' = 'Informatik, medizinische'
  '14'   = 'Innere Medizin'
  '458'  = 'Innere Medizin und Angiologie'
  '31'   = 'Innere Medizin und Endokrinologie und Diabetologie'
  '9'    = 'Innere Medizin und Gastroenterologie'
  '1269' = 'Innere Medizin und Geriatrie'
  '11'   = 'Innere Medizin und Haematologie und Onkologie'
  '4575' = 'Innere Medizin und Infektiologie'
  '15'   = 'Innere Medizin und Kardiologie'
  '22'   = 'Innere Medizin und Nephrologie'
  '20'   = 'Innere Medizin und Pneumologie'
  '28'   = 'Innere Medizin und Rheumatologie'
  '1412' = 'Intensivmedizin'
  '3792' = 'Kardiale Magnetresonanztomographie (Herz-MRT)'
  '3756' = 'Kardiologie -> Innere Medizin und Kardiologie'
  '214'  = 'Kieferorthopaedie'
  '1695' = 'Kinder- und Jugend-Endokrinologie und -Diabetologie'
  '1982' = 'Kinder- und Jugend-Gastroenterologie'
  '835'  = 'Kinder- und Jugend-Kardiologie'
  '1758' = 'Kinder- und Jugend-Nephrologie'
  '874'  = 'Kinder- und Jugend-Orthopaedie'
  '1773' = 'Kinder- und Jugend-Pneumologie'
  '1803' = 'Kinder- und Jugend-Rheumatologie'
  '1665' = 'Kinder- und Jugendlichenpsychotherapie'
  '17'   = 'Kinder-/Jugendpsychiatrie und -psychotherapie'
  '1668' = 'Kinder-Haematologie und -Onkologie'
  '927'  = 'Kinderchirurgie'
  '16'   = 'Kinderheilkunde / Kinder- und Jugendmedizin'
  '870'  = 'Kinderneurologie (Neuropaediatrie)'
  '1410' = 'Kinderradiologie'
  '2320' = 'Kinderzahnheilkunde (Kammerzertifikat)'
  '1666' = 'Klimatologie, medizinische -> Balneologie und Medizinische Klimatologie'
  '3793' = 'Klinische Akut- und Notfallmedizin'
  '3794' = 'Krankenhaushygiene'
  '1698' = 'Krebserkrankungen: Gynaekologische Onkologie'
  '1983' = 'Krebserkrankungen: Medikamentoese Tumortherapie'
  '19'   = 'Laboratoriumsmedizin'
  '1532' = 'Lungen- und Bronchialheilkunde -> Innere Medizin und Pneumologie'
  '2941' = 'Magnetresonanztomographie - fachgebunden'
  '486'  = 'Manualtherapie -> Manuelle Medizin / Chirotherapie'
  '5'    = 'Manuelle Medizin / Chirotherapie'
  '1442' = 'Mikrobiologie und Infektionsepidemiologie'
  '18'   = 'Mund-Kiefer-Gesichts-Chirurgie'
  '21'   = 'Naturheilverfahren'
  '1404' = 'Neonatologie / Neugeborenen-Medizin'
  '3757' = 'Nephrologie -> Innere Medizin und Nephrologie'
  '4437' = 'Nervenheilkunde'
  '1931' = 'Neugeborenen-Medizin -> Neonatologie / Neugeborenen-Medizin'
  '476'  = 'Neurochirurgie'
  '52'   = 'Neurologie'
  '3761' = 'Neurologie und Psychiatrie'
  '1335' = 'Neuropaediatrie -> Kinderneurologie'
  '1556' = 'Neuropathologie'
  '1079' = 'Neuroradiologie'
  '1497' = 'Nierenheilkunde -> Innere Medizin und Nephrologie'
  '1273' = 'Notfallmedizin'
  '24'   = 'Nuklearmedizin'
  '3795' = 'Nuklearmedizinische Diagnostik fuer Radiologen'
  '1613' = 'Oeffentliches Gesundheitswesen'
  '566'  = 'Oralchirurgie'
  '25'   = 'Orthopaedie'
  '2307' = 'Orthopaedie und Unfallchirurgie'
  '1437' = 'Palliativmedizin'
  '2910' = 'Parodontologie'
  '1232' = 'Pathologie'
  '1307' = 'Pharmakologie und Toxikologie'
  '1170' = 'Pharmakologie, klinische'
  '778'  = 'Phlebologie -> Venenheilkunde'
  '1414' = 'Phoniatrie und Paedaudiologie'
  '75'   = 'Physikalische Therapie und Balneologie'
  '507'  = 'Physikalische und Rehabilitative Medizin'
  '924'  = 'Physiologie'
  '246'  = 'Plastische Chirurgie'
  '2330' = 'Plastische und Aesthetische Chirurgie'
  '1458' = 'Plastische und Aesthetische Operationen'
  '3758' = 'Pneumologie -> Innere Medizin und Pneumologie'
  '798'  = 'Praktischer Arzt/Praktische Aerztin'
  '226'  = 'Proktologie -> Enddarmerkrankungen (Proktologie)'
  '23'   = 'Psychiatrie und Psychotherapie'
  '2331' = 'Psychiatrie: Forensische Psychiatrie'
  '27'   = 'Psychoanalyse'
  '1086' = 'Psychologische Psychotherapie'
  '1787' = 'Psychosomatische Medizin und Psychotherapie'
  '1144' = 'Psychotherapeutische Medizin'
  '53'   = 'Psychotherapie'
  '8'    = 'Radiologie'
  '1271' = 'Radiologie, Diagnostische -> Diagnostische Radiologie'
  '961'  = 'Rechtsmedizin'
  '431'  = 'Rehabilitationswesen'
  '3759' = 'Rheumatologie -> Innere Medizin und Rheumatologie'
  '2062' = 'Rheumatologie: Orthopaedische Rheumatologie'
  '3796' = 'Roentgendiagnostik fuer Nuklearmediziner'
  '1543' = 'Schlafmedizin'
  '1142' = 'Schmerztherapie: Spezielle Schmerztherapie'
  '3797' = 'Sexualmedizin'
  '1007' = 'Sozialmedizin'
  '3798' = 'Spezielle Kardiologie fuer Erwachsene mit angeborenen Herzfehlern'
  '3799' = 'Spezielle Kinder- und Jugendurologie'
  '29'   = 'Sportmedizin'
  '2912' = 'Sprach-, Stimm-, kindliche Hoerstoerungen -> Phoniatrie und Paedaudiologie'
  '925'  = 'Strahlentherapie'
  '2167' = 'Suchtmedizinische Grundversorgung'
  '4406' = 'Systemische Therapie (Richtlinie)'
  '4857' = 'Systemische Therapie fuer Kinder und Jugendliche (Richtlinie)'
  '2890' = 'Taetigkeitsschwerpunkt: Akupunktur'
  '2891' = 'Taetigkeitsschwerpunkt: Alterszahnheilkunde'
  '2892' = 'Taetigkeitsschwerpunkt: Angstpatienten'
  '2631' = 'Taetigkeitsschwerpunkt: Aesthetische Zahnheilkunde'
  '2893' = 'Taetigkeitsschwerpunkt: Behandlung fuer Menschen mit Behinderung'
  '2323' = 'Taetigkeitsschwerpunkt: Endodontologie'
  '2894' = 'Taetigkeitsschwerpunkt: Funktionsdiagnostik und -therapie'
  '2895' = 'Taetigkeitsschwerpunkt: Homoeopathie'
  '2896' = 'Taetigkeitsschwerpunkt: Hypnose'
  '2319' = 'Taetigkeitsschwerpunkt: Implantologie'
  '2284' = 'Taetigkeitsschwerpunkt: Kieferorthopaedie'
  '2899' = 'Taetigkeitsschwerpunkt: Laserbehandlung'
  '2900' = 'Taetigkeitsschwerpunkt: Oralchirurgie'
  '2041' = 'Taetigkeitsschwerpunkt: Parodontologie'
  '2897' = 'Taetigkeitsschwerpunkt: Prophylaxe'
  '2902' = 'Taetigkeitsschwerpunkt: Prothetik / Zahnersatz'
  '2903' = 'Taetigkeitsschwerpunkt: Umweltzahnmedizin'
  '1533' = 'Thoraxchirurgie -> Brustkorb-Chirurgie'
  '2905' = 'tiefenpsychol. fundierte Therapie (Richtlinie)'
  '3743' = 'tiefenpsychol. fundierte Therapie fuer Kinder und Jugendliche (Richtlinie)'
  '202'  = 'Transfusionsmedizin'
  '3800' = 'Transplantationsmedizin (Zusatzbezeichnung)'
  '1405' = 'Traumatologie -> Unfallchirurgie / Traumatologie'
  '1334' = 'Tropenmedizin'
  '2063' = 'Unfallchirurgie: Spezielle Unfallchirurgie'
  '30'   = 'Urologie'
  '56'   = 'Venenheilkunde (Phlebologie)'
  '2904' = 'Verhaltenstherapie (Richtlinie)'
  '3744' = 'Verhaltenstherapie fuer Kinder und Jugendliche (Richtlinie)'
  '1040' = 'Viszeralchirurgie -> Bauchchirurgie'
  '274'  = 'Zahnmedizin'
}

function Test-Fachgebiet {
  param([string]$Nummer)
  return $Global:Fachgebiete.Contains($Nummer)
}

function Get-FachgebietName {
  param([string]$Nummer)
  if ($Global:Fachgebiete.Contains($Nummer)) { return $Global:Fachgebiete[$Nummer] }
  return $null
}

function Show-FachgebietTabelle {
  # Sortiert nach numerischem Wert der Nummer, ausgegeben als "Nummer | Bezeichnung".
  Write-Host ''
  Write-Host 'Verfuegbare Fachgebiete (Nummer -> Bezeichnung):' -ForegroundColor Cyan
  Write-Host ('-' * 60)
  $Global:Fachgebiete.GetEnumerator() |
    Sort-Object { [int]$_.Key } |
    ForEach-Object { '{0,6}  {1}' -f $_.Key, $_.Value }
  Write-Host ('-' * 60)
}
